# Docker Compose file for running MongoDB and Mongo Express

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest # Use the latest official MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017" # Map the default MongoDB port to the host
    environment:
      # These credentials are for the MongoDB root user.
      # Mongo Express will use these to connect to the database.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db # Persist database data using a named volume

  # Mongo Express Service (Web-based admin interface for MongoDB)
  mongo-express:
    image: mongo-express:latest # Use the latest official Mongo Express image
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose the web interface on port 8081
    environment:
      # Configuration for connecting to the MongoDB service.
      # The ME_CONFIG_MONGODB_SERVER value must match the service name of the MongoDB container.
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # Use 'admin' as the default database for authentication.
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb # Ensures that the MongoDB service is started before Mongo Express

# Named volume for persisting MongoDB data
volumes:
  mongo-data:
    driver: local # Specifies the local driver for the volume
